Repository DeveloperAcademy-POSTECH/MC2-Team2-BurningBuddy, pull requests merged in 2023-05, with the labels that each got.

#4 Feature/#1
  BurningBuddy.xcodeproj/project.pbxproj
  BurningBuddy.xcodeproj/project.xcworkspace/contents.xcworkspacedata
  BurningBuddy.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  BurningBuddy/BurningBuddy/View/ContentView.swift
  BurningBuddy/BurningBuddyApp.swift
  BurningBuddy/Info.plist
  BurningBuddy/Model/Data.swift
  BurningBuddy/Preview Content/Preview Assets.xcassets/Contents.json
  BurningBuddy/Utils/Assets.xcassets/AccentColor.colorset/Contents.json
  BurningBuddy/Utils/Assets.xcassets/AppIcon.appiconset/Contents.json
  BurningBuddy/Utils/Assets.xcassets/Contents.json
  BurningBuddy/Utils/Assets.xcassets/Image.imageset/Contents.json
  BurningBuddy/Utils/Assets.xcassets/Image.imageset/Image.png
  BurningBuddy/Utils/Image.png
  BurningBuddy/Utils/cookie.jpeg
  BurningBuddy/View/CharacterSettingView.swift
  BurningBuddy/View/ContentView.swift
  BurningBuddy/View/EvolutionModalView.swift
  BurningBuddy/View/MainView.swift
  BurningBuddy/View/NicknameSettingView.swift
  BurningBuddy/View/SearchPartnerView.swift
  BurningBuddy/View/SettingView.swift
  BurningBuddy/View/WorkoutDoneView.swift
  BurningBuddy/View/WorkoutView.swift
Labels: ✨ Feat, ⚾️ Bazzi

#7 Feature/#2 뷰 파일 작업, 컴포넌트 배치
  BurningBuddy.xcodeproj/project.pbxproj
  BurningBuddy/Utils/Assets.xcassets/OnboardingTest1.imageset/Contents.json
  BurningBuddy/Utils/Assets.xcassets/OnboardingTest1.imageset/OnboardingTest1.png
  BurningBuddy/Utils/Assets.xcassets/OnboardingTest2.imageset/Contents.json
  BurningBuddy/Utils/Assets.xcassets/OnboardingTest2.imageset/OnboardingTest2.png
  BurningBuddy/Utils/Assets.xcassets/OnboardingTest3.imageset/Contents.json
  BurningBuddy/Utils/Assets.xcassets/OnboardingTest3.imageset/OnboardingTest3.png
  BurningBuddy/Utils/Assets.xcassets/OnboardingTest4.imageset/Contents.json
  BurningBuddy/Utils/Assets.xcassets/OnboardingTest4.imageset/OnboardingTest4.png
  BurningBuddy/Utils/OnboardingTest1.png
  BurningBuddy/Utils/OnboardingTest2.png
  BurningBuddy/Utils/OnboardingTest3.png
  BurningBuddy/Utils/OnboardingTest4.png
  BurningBuddy/View/Component/ButtonComponent.swift
  BurningBuddy/View/ContentView.swift
  BurningBuddy/View/LevelUp/LevelUpModalView.swift
  BurningBuddy/View/LevelUp/LevelUpView.swift
  BurningBuddy/View/Main/MainView.swift
  BurningBuddy/View/Main/SettingView.swift
  BurningBuddy/View/Onboarding/CalorieSettingView.swift
  BurningBuddy/View/Onboarding/CharacterSettingView.swift
  BurningBuddy/View/Onboarding/NicknameSettingView.swift
  BurningBuddy/View/Onboarding/OnboardingView.swift
  BurningBuddy/View/Partner/NotFoundPartnerView.swift
  BurningBuddy/View/Partner/SearchPartnerView.swift
  BurningBuddy/View/Workout/MissionCongratsView.swift
  BurningBuddy/View/Workout/MissionResultModalView.swift
  BurningBuddy/View/Workout/WorkoutDoneView.swift
  BurningBuddy/View/Workout/WorkoutView.swift
Labels: ➕ Add, ✨ Feat, ⚾️ Bazzi

#10 [Feat] NI, MPC, CoreData 필요한 파일 추가 및 구현
  BurningBuddy.xcodeproj/project.pbxproj
  BurningBuddy/Model/CoreData/Bunny+CoreDataClass.swift
  BurningBuddy/Model/CoreData/Bunny+CoreDataProperties.swift
  BurningBuddy/Model/CoreData/User+CoreDataClass.swift
  BurningBuddy/Model/CoreData/User+CoreDataProperties.swift
  BurningBuddy/Model/CoreData/UserDataModel.xcdatamodeld/UserDataModel.xcdatamodel/contents
  BurningBuddy/Model/Data.swift
  BurningBuddy/Model/FindingPartnerState.swift
  BurningBuddy/Resources/Assets.xcassets/AccentColor.colorset/Contents.json
  BurningBuddy/Resources/Assets.xcassets/AppIcon.appiconset/Contents.json
  BurningBuddy/Resources/Assets.xcassets/Contents.json
  BurningBuddy/Resources/Assets.xcassets/Image.imageset/Contents.json
  BurningBuddy/Resources/Assets.xcassets/Image.imageset/Image.png
  BurningBuddy/Resources/Assets.xcassets/OnboardingTest1.imageset/Contents.json
  BurningBuddy/Resources/Assets.xcassets/OnboardingTest1.imageset/OnboardingTest1.png
  BurningBuddy/Resources/Assets.xcassets/OnboardingTest2.imageset/Contents.json
  BurningBuddy/Resources/Assets.xcassets/OnboardingTest2.imageset/OnboardingTest2.png
  BurningBuddy/Resources/Assets.xcassets/OnboardingTest3.imageset/Contents.json
  BurningBuddy/Resources/Assets.xcassets/OnboardingTest3.imageset/OnboardingTest3.png
  BurningBuddy/Resources/Assets.xcassets/OnboardingTest4.imageset/Contents.json
  BurningBuddy/Resources/Assets.xcassets/OnboardingTest4.imageset/OnboardingTest4.png
  BurningBuddy/Resources/Image.png
  BurningBuddy/Resources/OnboardingTest1.png
  BurningBuddy/Resources/OnboardingTest2.png
  BurningBuddy/Resources/OnboardingTest3.png
  BurningBuddy/Resources/OnboardingTest4.png
  BurningBuddy/Resources/cookie.jpeg
  BurningBuddy/Utils/.gitkeep
  BurningBuddy/Utils/CoreDataManager.swift
  BurningBuddy/Utils/NIUtils/LocalNetworkAuthorization.swift
  BurningBuddy/Utils/NIUtils/MPCUtils/MPCSession.swift
  BurningBuddy/Utils/NIUtils/NISessionManager.swift
Labels: ➕ Add, ✨ Feat, 🎱 West

#14 [Feat] #8 - HealthKit 권한 설정 기능 추가
  BurningBuddy.xcodeproj/project.pbxproj
  BurningBuddy/Model/WorkoutData.swift
Labels: ✨ Feat, 🏀 Jay

#15 [Chore] #9 - NI, MPC 코드 정리
  BurningBuddy.xcodeproj/project.pbxproj
  BurningBuddy/Model/CoreData/Bunny+CoreDataClass.swift
  BurningBuddy/Model/CoreData/Bunny+CoreDataProperties.swift
  BurningBuddy/Model/CoreData/User+CoreDataClass.swift
  BurningBuddy/Model/CoreData/User+CoreDataProperties.swift
  BurningBuddy/Model/CoreData/UserDataModel.xcdatamodeld/UserDataModel.xcdatamodel/contents
  BurningBuddy/Utils/CoreDataManager.swift
  BurningBuddy/Utils/NIUtils/LocalNetworkAuthorization.swift
  BurningBuddy/Utils/NIUtils/NISessionManager.swift
Labels: ✏️ Chore, 🥎 Luna

#16 [Feat] #8 - HealthKit 운동 시작시간 기록, 운동기록 가져오는 기능 추가
  BurningBuddy/Model/WorkoutData.swift
Labels: ✨ Feat, 🏀 Jay

#21 [Feat] #11 - 온보딩 로직, CoreData가져오기
  BurningBuddy.xcodeproj/project.pbxproj
  BurningBuddy/Model/CoreData/Bunny/Bunny+CoreDataClass.swift
  BurningBuddy/Model/CoreData/Bunny/Bunny+CoreDataProperties.swift
  BurningBuddy/Model/CoreData/User/User+CoreDataClass.swift
  BurningBuddy/Model/CoreData/User/User+CoreDataProperties.swift
  BurningBuddy/Model/CoreData/UserDataModel.xcdatamodeld/UserDataModel.xcdatamodel/contents
  BurningBuddy/Utils/CoreDataManager.swift
  BurningBuddy/Utils/NIUtils/NISessionManager.swift
  BurningBuddy/View/ContentView.swift
  BurningBuddy/View/LevelUp/LevelUpModalView.swift
  BurningBuddy/View/LevelUp/LevelUpView.swift
  BurningBuddy/View/Main/MainView.swift
  BurningBuddy/View/Main/SettingView.swift
  BurningBuddy/View/Onboarding/CalorieSettingView.swift
  BurningBuddy/View/Onboarding/CharacterSettingView.swift
  BurningBuddy/View/Onboarding/NicknameSettingView.swift
  BurningBuddy/View/Onboarding/OnboardingView.swift
  BurningBuddy/View/Partner/NotFoundPartnerView.swift
  BurningBuddy/View/Partner/SearchPartnerView.swift
  BurningBuddy/View/Workout/MissionCongratsView.swift
  BurningBuddy/View/Workout/MissionResultModalView.swift
  BurningBuddy/View/Workout/WorkoutDoneView.swift
  BurningBuddy/View/Workout/WorkoutView.swift
Labels: ✨ Feat, 🥎 Luna

#19 [Feat] #12 - Character 진화 View
  BurningBuddy.xcodeproj/project.pbxproj
  BurningBuddy/Resources/Assets.xcassets/Close.imageset/Close.png
  BurningBuddy/Resources/Assets.xcassets/Close.imageset/Contents.json
  BurningBuddy/Resources/Assets.xcassets/EvolutionRoadmap.imageset/Contents.json
  BurningBuddy/Resources/Assets.xcassets/EvolutionRoadmap.imageset/EvolutionRoadmap.png
  BurningBuddy/Resources/Assets.xcassets/dumbell.imageset/Contents.json
  BurningBuddy/Resources/Assets.xcassets/dumbell.imageset/􁖍.png
  BurningBuddy/View/Component/ButtonComponent.swift
  BurningBuddy/View/LevelUp/LevelUpModalView.swift
  BurningBuddy/View/LevelUp/LevelUpStepView.swift
  BurningBuddy/View/Main/MainView.swift
Labels: ✨ Feat, ⚽️ Muho

#23 [Feat] NI, MPC UI에 연결
  BurningBuddy.xcodeproj/project.pbxproj
  BurningBuddy/BurningBuddyApp.swift
  BurningBuddy/Info.plist
  BurningBuddy/Resources/Assets.xcassets/ColorSet/Contents.json
  BurningBuddy/Resources/Assets.xcassets/ColorSet/MainTextColor.colorset/Contents.json
  BurningBuddy/Resources/Assets.xcassets/ColorSet/SubTextColor.colorset/Contents.json
  BurningBuddy/Resources/Assets.xcassets/ColorSet/backgroundColor.colorset/Contents.json
  BurningBuddy/Resources/Assets.xcassets/ColorSet/iconColor.colorset/Contents.json
  BurningBuddy/Resources/Assets.xcassets/ColorSet/mainSection.colorset/Contents.json
  BurningBuddy/Resources/Assets.xcassets/ColorSet/mainSection2.colorset/Contents.json
  BurningBuddy/Resources/Assets.xcassets/ColorSet/primary.colorset/Contents.json
  BurningBuddy/Resources/Assets.xcassets/ColorSet/primarySub.colorset/Contents.json
  BurningBuddy/Resources/Assets.xcassets/ColorSet/subGray.colorset/Contents.json
  BurningBuddy/Utils/NIUtils/NISessionManager.swift
  BurningBuddy/View/Component/ColorExtension.swift
  BurningBuddy/View/ContentView.swift
  BurningBuddy/View/LevelUp/LevelUpView.swift
  BurningBuddy/View/Main/MainView.swift
  BurningBuddy/View/Onboarding/CalorieSettingView.swift
  BurningBuddy/View/Onboarding/CharacterSettingView.swift
  BurningBuddy/View/Onboarding/NicknameSettingView.swift
  BurningBuddy/View/Onboarding/OnboardingView.swift
  BurningBuddy/View/Partner/SearchPartnerView.swift
  BurningBuddy/View/Workout/MissionCongratsComponent.swift
  BurningBuddy/View/Workout/MissionResultModalView.swift
  BurningBuddy/View/Workout/WorkoutDoneView.swift
  BurningBuddy/View/Workout/WorkoutFailView.swift
  BurningBuddy/View/Workout/WorkoutSuccessView.swift
  BurningBuddy/View/Workout/WorkoutView.swift
Labels: ✨ Feat, 🛠️ Fix, 🎱 West

#28 [Feat] #25 - 온보딩 페이지 완성
  BurningBuddy.xcodeproj/project.pbxproj
  BurningBuddy/Resources/Assets.xcassets/ColorSet/bunnyColor.colorset/Contents.json
  BurningBuddy/Resources/Assets.xcassets/ColorSet/bunnyColorSub.colorset/Contents.json
  BurningBuddy/Resources/Assets.xcassets/ColorSet/iconColor.colorset/Contents.json
  BurningBuddy/Resources/Assets.xcassets/Onboarding1.imageset/Contents.json
  BurningBuddy/Resources/Assets.xcassets/Onboarding1.imageset/Onboarding1.png
  BurningBuddy/Resources/Assets.xcassets/Onboarding2.imageset/Contents.json
  BurningBuddy/Resources/Assets.xcassets/Onboarding2.imageset/Onboarding2.png
  BurningBuddy/Resources/Assets.xcassets/Onboarding3.imageset/Contents.json
  BurningBuddy/Resources/Assets.xcassets/Onboarding3.imageset/Onboarding3.png
  BurningBuddy/Resources/Assets.xcassets/OnboardingTest1.imageset/OnboardingTest1.png
  BurningBuddy/Resources/Assets.xcassets/OnboardingTest2.imageset/OnboardingTest2.png
  BurningBuddy/Resources/Assets.xcassets/OnboardingTest3.imageset/OnboardingTest3.png
  BurningBuddy/Resources/Onboarding1.png
  BurningBuddy/Resources/Onboarding2.png
  BurningBuddy/Resources/Onboarding3.png
  BurningBuddy/Resources/OnboardingTest1.png
  BurningBuddy/Resources/OnboardingTest2.png
  BurningBuddy/Resources/OnboardingTest3.png
  BurningBuddy/View/Component/ButtonComponent.swift
  BurningBuddy/View/Component/ColorExtension.swift
  BurningBuddy/View/ContentView.swift
  BurningBuddy/View/LevelUp/LevelUpModalView.swift
  BurningBuddy/View/LevelUp/LevelUpView.swift
  BurningBuddy/View/Main/MainView.swift
  BurningBuddy/View/Main/SettingView.swift
  BurningBuddy/View/Onboarding/CalorieSettingView.swift
  BurningBuddy/View/Onboarding/CharacterSettingView.swift
  BurningBuddy/View/Onboarding/NicknameSettingView.swift
  BurningBuddy/View/Onboarding/OnboardingView.swift
  BurningBuddy/View/Partner/NotFoundPartnerView.swift
  BurningBuddy/View/Partner/SearchPartnerView.swift
  BurningBuddy/View/Workout/MissionCongratsComponent.swift
  BurningBuddy/View/Workout/MissionResultModalView.swift
  BurningBuddy/View/Workout/WorkoutDoneView.swift
  BurningBuddy/View/Workout/WorkoutView.swift
Labels: ✨ Feat, ⚾️ Bazzi

#30 [Hotfix] #24 - 파트너찾기 NI 오류 해결
  BurningBuddy.xcodeproj/project.pbxproj
  BurningBuddy/Info.plist
  BurningBuddy/Model/WorkoutData.swift
  BurningBuddy/Utils/NIUtils/MPCUtils/MPCSession.swift
  BurningBuddy/Utils/NIUtils/NISessionManager.swift
Labels: 🚑️ Hotfix, 🥎 Luna, 🎱 West

#33 Feature/#25
  BurningBuddy/View/ContentView.swift
  BurningBuddy/View/LevelUp/LevelUpModalView.swift
  BurningBuddy/View/LevelUp/LevelUpView.swift
  BurningBuddy/View/Main/MainView.swift
  BurningBuddy/View/Onboarding/CharacterSettingView.swift
  BurningBuddy/View/Onboarding/NicknameSettingView.swift
  BurningBuddy/View/Partner/SearchPartnerView.swift
  BurningBuddy/View/Workout/MissionCongratsComponent.swift
  BurningBuddy/View/Workout/MissionResultModalView.swift
  BurningBuddy/View/Workout/WorkoutDoneView.swift
  BurningBuddy/View/Workout/WorkoutFailView.swift
  BurningBuddy/View/Workout/WorkoutSuccessView.swift
  BurningBuddy/View/Workout/WorkoutView.swift
Labels: ✨ Feat, ⚾️ Bazzi

#35 Update README.md
  README.md
Labels: 📝 Docs

#40 Feature/#39
  BurningBuddy.xcodeproj/project.pbxproj
  BurningBuddy/View/Component/ButtonComponent.swift
  BurningBuddy/View/Main/MainView.swift
  BurningBuddy/View/Partner/SearchPartnerView.swift
  BurningBuddy/View/Workout/MissionCongratsComponent.swift
  BurningBuddy/View/Workout/MissionResultModalView.swift
  BurningBuddy/View/Workout/WorkoutDoneView.swift
  BurningBuddy/View/Workout/WorkoutFailView.swift
  BurningBuddy/View/Workout/WorkoutSuccessView.swift
  BurningBuddy/View/Workout/WorkoutView.swift
Labels: ✨ Feat, ⚾️ Bazzi

#41 Feat/#32
  BurningBuddy/BurningBuddy.entitlements
  BurningBuddy/View/ContentView.swift
  BurningBuddy/View/Main/MainView.swift
  BurningBuddy/View/Partner/SearchPartnerView.swift
  BurningBuddy/View/Workout/WorkoutView.swift
Labels: ✨ Feat, 🏀 Jay

#43 [Fix] #42 - View 도르마무 임시 해결
  BurningBuddy.xcodeproj/project.pbxproj
  BurningBuddy/Model/WorkoutData.swift
  BurningBuddy/View/ContentView.swift
  BurningBuddy/View/Workout/WorkoutView.swift
Labels: 🛠️ Fix, 🏀 Jay

#50 Feature/#46 새로운 날이 되었으면 운동 관련 데이터 초기화
  BurningBuddy.xcodeproj/project.pbxproj
  BurningBuddy/BurningBuddyApp.swift
  BurningBuddy/Model/CoreData/User/User+CoreDataProperties.swift
  BurningBuddy/Model/CoreData/UserDataModel.xcdatamodeld/UserDataModel.xcdatamodel/contents
  BurningBuddy/Utils/CoreDataManager.swift
  BurningBuddy/Utils/NIUtils/NISessionManager.swift
  BurningBuddy/View/ContentView.swift
  BurningBuddy/View/Main/MainView.swift
  BurningBuddy/View/Partner/SearchPartnerView.swift
  BurningBuddy/View/Workout/DataReceiveView.swift
  BurningBuddy/View/Workout/MissionCongratsComponent.swift
  BurningBuddy/View/Workout/MissionResultModalView.swift
  BurningBuddy/View/Workout/WorkoutDoneView.swift
  BurningBuddy/View/Workout/WorkoutView.swift
Labels: ✨ Feat, 🥎 Luna

#56 [Feat] #36 - 운동 종료 후 NI 재실행, 파트너 목표 달성 여부 확인
  BurningBuddy/Utils/NIUtils/NISessionManager.swift
  BurningBuddy/View/Partner/SearchPartnerView.swift
  BurningBuddy/View/Workout/DataReceiveView.swift
  BurningBuddy/View/Workout/WorkoutDoneView.swift
Labels: ✨ Feat, ⚾️ Bazzi, 🎱 West

#58 [Hotfix] #57 - CoreData가 비어있는 상태에서 read를 해서 오류가 생기는 문제 해결
  BurningBuddy.xcodeproj/project.pbxproj
  BurningBuddy/View/ContentView.swift
  BurningBuddy/View/Main/MainView.swift
  BurningBuddy/View/Onboarding/LevelUp/LevelUpModalView.swift
  BurningBuddy/View/Onboarding/LevelUp/LevelUpStepView.swift
  BurningBuddy/View/Onboarding/LevelUp/LevelUpView.swift
Labels: 🚑️ Hotfix, 🥎 Luna

#65 [Hotfix] #62 - 운동 시간 String 00h 00m으로 변경
  BurningBuddy/Model/WorkoutData.swift
  BurningBuddy/Utils/CoreDataManager.swift
  BurningBuddy/View/ContentView.swift
  BurningBuddy/View/Main/MainView.swift
  BurningBuddy/View/Workout/WorkoutView.swift
Labels: 🚑️ Hotfix, 🏀 Jay

#68 [Add] #66 - 온보딩 4페이지 캐릭터 이미지 변경, 레벨업 뷰 캐릭터 정면 -> 반측면으로 변경
  BurningBuddy/BurningBuddyApp.swift
  BurningBuddy/Resources/Assets.xcassets/Onboarding4.imageset/Contents.json
  BurningBuddy/Resources/Assets.xcassets/Onboarding4.imageset/Onboarding4.png
  BurningBuddy/View/LevelUp/LevelUpView.swift
  BurningBuddy/View/Onboarding/OnboardingView.swift
Labels: ➕ Add

#70 [Fix] #69 - 파트너 연결 및 연결완료 뷰 부분의 UI 수정
  BurningBuddy/Resources/Assets.xcassets/circleImage.imageset/Contents.json
  BurningBuddy/Resources/Assets.xcassets/circleImage.imageset/circleImage.png
  BurningBuddy/Resources/Assets.xcassets/person-fill.imageset/Contents.json
  BurningBuddy/Resources/Assets.xcassets/person-fill.imageset/person-fill.png
  BurningBuddy/View/Partner/LoadingAnimationView.swift
  BurningBuddy/View/Partner/SearchPartnerView.swift
Labels: 🛠️ Fix, 🏀 Jay

#78 [Add] #77 - 메인뷰 및 이미지와 버튼 크기 조절
  BurningBuddy/BurningBuddyApp.swift
  BurningBuddy/Resources/Assets.xcassets/Onboarding/Onboarding4.imageset/Onboarding4.png
  BurningBuddy/View/Component/ButtonComponent.swift
  BurningBuddy/View/Main/MainView.swift
  BurningBuddy/View/Onboarding/OnboardingView.swift
  BurningBuddy/View/Partner/SearchPartnerView.swift
  BurningBuddy/View/Workout/MissionCongratsComponent.swift
  BurningBuddy/View/Workout/MissionResultModalView.swift
  BurningBuddy/View/Workout/WorkoutDoneView.swift
Labels: ✨ Feat, ⚽️ Muho

#85 [Docs] README 프로젝트 기간 위치 변경
  README.md
Labels: 📝 Docs, 🥎 Luna

#86 [Docs] Readme 업데이트
  README.md
Labels: 📝 Docs, 🥎 Luna, 🎱 West
